### ISSUE TITLE
Cannot parse GEOMETRYCOLLECTION

### ISSUE THREAD

**Issue by hahuy** [Esri/terraformer-wkt-parser#18] opened 2016-07-28 03:03 UTC
Uncaught Error: Unable to parse: Error: Parse error on line 1:
GEOMETRYCOLLECTION(L
^
Expecting 'POINT', 'LINESTRING', 'POLYGON', 'MULTIPOINT', 'MULTILINESTRING', 'MULTIPOLYGON', got 'INVALID'

**Comment by jgravois** [comment] 2016-07-28 04:31
this is more or less a duplicate of #16.

we should probably clarify this point in the documentation.

**Comment by jgravois** [comment] 2016-07-28 18:20
this is more or less a duplicate of #16.

we should probably clarify this point in the documentation.

**Comment by jgravois** [comment] 2016-07-29 23:35
we now explicitly call out acceptable WKT geometry types to pass to `parse()` in the documentation site.

http://terraformer.io/wkt-parser/#wktparse

i'll go ahead and close this issue, but i'd be happy to chat more if you have any additional questions.  either way, look for support for converting GeoJSON GeometryCollections in our next release! #19

**Closed by jgravois** 2016-07-29 23:35 UTC
